### ISSUE TITLE
Duplicate Patch Files for Class Descriptions for Antennas

### ISSUE THREAD

**Issue by PadroneSF** [linuxgurugamer/FilterExtension#58]
In the directory 'zFinal_Filter_Extensions', there are two .CFG files that add Class Descriptions to Antenna parts.  This results in the first two sentences of the description being duplicate class descriptions.

**Comment by linuxgurugamer** [comment]
For all parts/antennas?
And are you using RemoteTech?

**Comment by linuxgurugamer** [comment]
Also, can you be specific as to the files?  I just looked at both files, I don't see a duplication (yet)

**Comment by PadroneSF** [comment]
Yes, for all parts that have ModuleDataTransmitter*, the class description is displayed twice in the part description.  Here's an example:  [https://imgur.com/GD09Mjv](url).

I'm not using Remote Tech, tho a RT installation will have the same issue, I'm sure.

The entire files are duplicates of each other.  (I ran them through [https://www.diffchecker.com/text-compare](url)  just to make sure my eyeballs didn't miss a difference.)  It reports them as being identical.

So both files insert the antenna class description text. Hence the duplicate text in the VAB for anything that has an antenna.  

Removing one of the files will have the added benefit of removing 16 passes of a @PART[*] run for a non-RT installation.  With all the mods I'm running, I'll take any opportunity to cut down the load time!

**Comment by linuxgurugamer** [comment]
I'm sorry, I don't see that in the files in the mod.  The  two files here are:

zzz_AntennaClassDescriptions.cfg   7k
zzz_RemoteTechAddMissingModuleSPUPassive.cfg  23k

Can you please check your system and see if you have duplicated files?  It's possible that at some point the files were renamed and you ended up with two copies

**Comment by PadroneSF** [comment]
My bad. I have 3.2.7 installed, which has both files.  Now that I looked at the history, 3.2.7.1 actually addressed my issue directly.

Sorry to have wasted your time!
